eureka:
  client:
    registry-fetch-interval-seconds: 8
    serviceUrl:
      defaultZone: http://10.110.3.206:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: refresh,info,health,metrics,prometheus
logging:
  config: classpath:log4j2.xml

ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000

feign:
  client:
    config:
      default:
        connectTimeout: 90000
        readTimeout: 90000

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl